import nodemailer from 'nodemailer';

interface EmailOptions {
  to: string;
  subject: string;
  html: string;
}

let transporter: nodemailer.Transporter | null = null;

function getTransporter() {
  if (transporter) return transporter;
  
  transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST || 'smtp.gmail.com',
    port: parseInt(process.env.SMTP_PORT || '587'),
    secure: false,
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });
  
  return transporter;
}

export async function sendEmail(options: EmailOptions): Promise<boolean> {
  try {
    if (!process.env.SMTP_USER || !process.env.SMTP_PASS) {
      console.warn('SMTP credentials not configured. Email not sent.');
      return false;
    }
    
    const mailTransporter = getTransporter();
    
    await mailTransporter.sendMail({
      from: process.env.SMTP_FROM || process.env.SMTP_USER,
      to: options.to,
      subject: options.subject,
      html: options.html,
    });
    
    return true;
  } catch (error) {
    console.error('Error sending email:', error);
    return false;
  }
}

export function generateBreachAlertEmail(
  serviceName: string,
  breachDetails: string[],
  passwordEntryId: string
): string {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .alert { background-color: #fee; border-left: 4px solid #f00; padding: 15px; margin: 20px 0; }
        .button { display: inline-block; padding: 10px 20px; background-color: #007bff; color: white; text-decoration: none; border-radius: 5px; margin-top: 20px; }
      </style>
    </head>
    <body>
      <div class="container">
        <h2>🚨 Security Alert: Password Breach Detected</h2>
        <div class="alert">
          <h3>Your password for "${serviceName}" has been found in a data breach!</h3>
          <p><strong>Breach Details:</strong></p>
          <ul>
            ${breachDetails.map(detail => `<li>${detail}</li>`).join('')}
          </ul>
        </div>
        <p><strong>Action Required:</strong></p>
        <ol>
          <li>Immediately change your password for this service</li>
          <li>Use a strong, unique password generated by the Password Generator</li>
          <li>Consider enabling two-factor authentication if available</li>
        </ol>
        <p>Please log into the Password Generator application to generate a new secure password and update your records.</p>
        <p>Stay safe!</p>
      </div>
    </body>
    </html>
  `;
}

